package com.liguo.hgl.proxydao.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.liguo.hgl.proxydao.base.BaseMapper;
import com.liguo.hgl.proxydao.model.Criteria;
import com.liguo.hgl.proxydao.model.ProductImport;
import com.liguo.hgl.proxydao.model.TbProductType;

public interface TbProductTypeMapper extends BaseMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated Tue Mar 29 16:37:44 CST 2016
     */
    int countByExample(Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated Tue Mar 29 16:37:44 CST 2016
     */
    int deleteByExample(Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated Tue Mar 29 16:37:44 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated Tue Mar 29 16:37:44 CST 2016
     */
    int insert(TbProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated Tue Mar 29 16:37:44 CST 2016
     */
    int insertSelective(TbProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated Tue Mar 29 16:37:44 CST 2016
     */
    List<TbProductType> selectByExample(Criteria example);

    /**
     * @Description:二级分类更新时，级联更新三级分类
     * @author:ZK 
     * @date:2016-7-18
     * @parameter:
     * @return: int
      */
    int updateProductTyppeByPrimaryKeyArray(Criteria example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated Tue Mar 29 16:37:44 CST 2016
     */
    TbProductType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated Tue Mar 29 16:37:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") TbProductType record, @Param("example") Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated Tue Mar 29 16:37:44 CST 2016
     */
    int updateByExample(@Param("record") TbProductType record, @Param("example") Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated Tue Mar 29 16:37:44 CST 2016
     */
    int updateByPrimaryKeySelective(TbProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_type
     *
     * @mbggenerated Tue Mar 29 16:37:44 CST 2016
     */
    int updateByPrimaryKey(TbProductType record);
    
    /**
     * 根据类别Id查询对应的品名
     * @param productTypeId
     * @return
     * @author zss
     */
	List<TbProductType> selectProductTypeByMinId(Integer productTypeId);
	
	
	List<ProductImport> findNotParentId(Criteria criteria) ;
	
	int findNotParentIdCount() ;
	
	/**
	 * 
	 * 附近的店铺类型
	 * */
	public List<TbProductType> selectNearShopType();
    
}