TRUNCATE TABLE tb_account;
TRUNCATE TABLE tb_account_bank;
TRUNCATE TABLE tb_activity_info;
TRUNCATE TABLE tb_address;
TRUNCATE TABLE tb_address_history;
##TRUNCATE TABLE tb_admin_permission;
##TRUNCATE TABLE tb_admin_role;
delete  from tb_admin_user where id<>1;
TRUNCATE TABLE tb_agency;
TRUNCATE TABLE tb_album_space;
TRUNCATE TABLE tb_brand;
TRUNCATE TABLE tb_cash_account;
##TRUNCATE TABLE tb_city_info;
TRUNCATE TABLE tb_city_lowest_price;
##TRUNCATE TABLE tb_country_info;
TRUNCATE TABLE tb_coupon_info;
TRUNCATE TABLE tb_customer_service;
TRUNCATE TABLE tb_delivery_terms;
##TRUNCATE TABLE tb_dict;
TRUNCATE TABLE tb_experience;
TRUNCATE TABLE tb_freezing;
TRUNCATE TABLE tb_heart_beat;
TRUNCATE TABLE tb_integral;
TRUNCATE TABLE tb_integral_detailed;
TRUNCATE TABLE tb_inventory_lock;
TRUNCATE TABLE tb_manualorder_detail;
TRUNCATE TABLE tb_merch_notice;
TRUNCATE TABLE tb_merchants;
TRUNCATE TABLE tb_notice_info;
TRUNCATE TABLE tb_opened_regional;
TRUNCATE TABLE tb_order_detail;
TRUNCATE TABLE tb_order_group;
TRUNCATE TABLE tb_order_tracking;
TRUNCATE TABLE tb_pay_context_param;
##TRUNCATE TABLE tb_pay_param_message;
TRUNCATE TABLE tb_pay_water;
TRUNCATE TABLE tb_product;
TRUNCATE TABLE tb_product_inventory;
TRUNCATE TABLE tb_product_type;
TRUNCATE TABLE tb_program_info;
TRUNCATE TABLE tb_program_praise;
##TRUNCATE TABLE tb_province_info;
TRUNCATE TABLE tb_recommended;
TRUNCATE TABLE tb_recommended_rules;
##TRUNCATE TABLE tb_recommended_type;
TRUNCATE TABLE tb_save_info;
TRUNCATE TABLE tb_service_type;
TRUNCATE TABLE tb_shop_info;
##TRUNCATE TABLE tb_shop_level;
TRUNCATE TABLE tb_shop_user_ref;
TRUNCATE TABLE tb_shopping_cart;
TRUNCATE TABLE tb_statistical;
##TRUNCATE TABLE tb_street_info;
DROP TABLE tb_sys_seq_no;
##TRUNCATE TABLE tb_system_config;
TRUNCATE TABLE tb_talk;
TRUNCATE TABLE tb_user_group;
TRUNCATE TABLE tb_user_info;
TRUNCATE TABLE tb_wap_address;
TRUNCATE TABLE tb_wap_address_history;
TRUNCATE TABLE tb_wap_inventory_lock;
TRUNCATE TABLE tb_wap_order_detail;
TRUNCATE TABLE tb_wap_order_group;
TRUNCATE TABLE tb_wap_order_service;
TRUNCATE TABLE tb_wap_order_service_detail;
TRUNCATE TABLE tb_wap_order_tracking;
TRUNCATE TABLE tb_wap_order_tracking_service;
TRUNCATE TABLE tb_wap_product;
TRUNCATE TABLE tb_wap_product_inventory;
TRUNCATE TABLE tb_wap_shopping_cart;
TRUNCATE TABLE tb_warehouse;
TRUNCATE TABLE tb_warehouse_user;
##TRUNCATE TABLE tb_web_permission;
##TRUNCATE TABLE tb_web_role;
TRUNCATE TABLE tb_web_user;
TRUNCATE TABLE tb_weixin_pass_user;
TRUNCATE TABLE tb_weixin_user;
TRUNCATE TABLE tb_withdrawals;

INSERT INTO `tb_account` VALUES ('1', '0', '0', null, null, null, null, '0');
INSERT INTO `tb_shop_info` VALUES ('1', '104', '1', '0', '惠给利', null, '惠给利', '400-6718-278', null, null, '440000', '440300', '440312', '440312002', '展涛科技大厦1201', null, null, '五金机电', '0', null, null, null, 'shopImage1.jpg', null, null, null, null, '0', null, '1468221129182', '0', '0', '0', '0', '114.038424', '22.6392031', '0', '1', '0', null, '0', null, null);
INSERT INTO `tb_web_user` VALUES ('1', 'hgl', '96e79218965eb72c92a549dd5a330112', null, null, '400-6718-278', '李国栋', 1, '104', '1', null, null, null, null, '1', null, '0000', '0000', '1', null, null, '1468221129255');
INSERT INTO `tb_system_config` VALUES ('1', 'automitcTime', '7', '收货间隔的毫秒值', '0', NULL, '0', NULL, '0', NULL, '0');
INSERT INTO `tb_system_config` VALUES ('2', '500', '500', NULL, '0', '1', '1', '', '1', NULL, '0');
INSERT INTO `hgl`.`tb_system_config` (`id`, `config_key`, `config_value`, `remark`, `create_dt`, `update_dt`) VALUES (4, 'settlement', '0.1', '结算服务权限购买金额', 0, 0);
INSERT INTO `tb_system_config` VALUES ('5', 'clearArchive', '1', '清除压缩包重复名称的天数', '0', NULL, '0', NULL, '0', NULL, '0');
INSERT INTO `tb_system_config` VALUES ('6', 'signIntegral', '20', '一次签到获得的积分', '0', null, '0', 'admin', '0', null, '0');
INSERT INTO `tb_pay_param_message`  VALUES ('1', '1', '微信支付', ' ', NULL, 'http://wap.hgeili.com/payCallBack/weixinPay', NULL, NULL, NULL, 'http://wap.hgeili.com/weixinPay/goPay', NULL);
INSERT INTO `tb_pay_param_message` (`id`, `pay_type_code`, `pay_type_name`, `pay_get_code`, `pay_notify_url`, `pay_return_url`, `pay_ip`, `pay_port`, `pay_encode`, `pay_addr`, `pay_key`) VALUES ('2', '2', '微信扫码支付', NULL, NULL, 'http://wap.hgeili.com/payCallBack/weixinPay', NULL, NULL, NULL, 'http://wap.hgeili.com/weixinPay/nativePay', NULL);

